version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "8081:8081"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydatabase

  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mantastyle1

volumes:
  db-data:
